-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "youtubeUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "facebookUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "instagramUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "spotifyUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "appleMusicUrl" TEXT NOT NULL DEFAULT '';
